# Configuration file path of logging
log_cfg: logging.yml
# IP addr and port of master and workers
addr:
  master: 'localhost:12120'
  worker:
    # key is worker_id, which must be int
    0: 'localhost:12110'
    1: 'localhost:12111'
# DNN load function, use this to choose dnn
dnn_loader: !!python/name:dnn_models.chain.prepare_alexnet
# Path of the input video file
video_path: media/road.mp4
# Adjust the input frame to [nrow, ncol], which is a tuple of two int. None indicates don't resize.
frame_size: !!python/tuple [1080, 1920]
# Whether check the correctness of result
check: !!bool true
# Configuration of master
master:
# Configuration of worker
worker: