# Configuration file path of logging
log_cfg: logging.yml
# IP addr and port of master and workers
addr:
  master: 'localhost:12120'
  worker:
    # key is worker_id, which must be continuously increased from 0
    # Workers are sorted by execution order
    0: 'localhost:12110'
    1: 'localhost:12111'
    2: 'localhost:12112'
  trainer: 'localhost:12100'
# DNN load function, use this to choose dnn
dnn_loader: !!python/name:dnn_models.chain.prepare_alexnet
# Path of the input video file
video_path: media/road.mp4
# Adjust the input frame to [nrow, ncol], which is a tuple of two int. None indicates don't resize.
frame_size: !!python/tuple [480, 720]
# Whether check the correctness of result
check: !!bool true
# Configuration of master
master:
  ifr_num: 5  # Total frame to be processed
  pd_num: 2  # How many frames are pending at the same time, 0 means unlimited
  itv_time: 3  # How long to wait after issuing an IFR, for debugging only. Normally it should be 0
  scheduler:
    # len(bandwidth) must be equal to len(worker).
    # bandwidth[w] = bandwidth(MB) between w-1 and w. bandwidth[0] refers to master and worker0.
    bandwidth: [1, 1, 1]
# Configuration of worker
worker:
  prof_niter: 5
# Configuration of trainer
trainer:
  frame_num: 400